In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('customers.csv')
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [3]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

In [4]:
value_counts = df['y'].value_counts()
value_counts

y
no     39922
yes     5289
Name: count, dtype: int64

In [5]:
from imblearn.over_sampling import RandomOverSampler

input_colums = df.drop('y',axis=1)

class_coulums = df['y']

oversampler = RandomOverSampler(random_state=0)
input_colums_resampled , class_coulums_resampled = oversampler.fit_resample(input_colums, class_coulums)

df = pd.concat([input_colums_resampled , class_coulums_resampled])

In [6]:
class_distribuition = df['y'].value_counts()
class_distribuition

y
no     39922
yes    39922
Name: count, dtype: int64

In [7]:
X =df.iloc[:,0:16].values

y = df.iloc[:,-1]

In [8]:
from sklearn.preprocessing import   LabelEncoder

labelencoder_y = LabelEncoder()

y = labelencoder_y.fit_transform(y)

In [9]:
print(y)

[2 2 2 ... 1 1 1]

In [10]:
X_job = X[:,[1]]
print(X_job)

[['management']
 ['technician']
 ['entrepreneur']
 ...
 [nan]
 [nan]
 [nan]]

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], sparse_threshold=0)


X_job = ct.fit_transform(X_job)

print(X_job)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]

In [12]:
X_cat = X[:,[1,2,3,4,5,6,7,8,10,15]]

In [ ]:
orginalNumOfCols = X_cat.shape[1]

for i in range(X_cat.shape[1]): 
    
    currNumOfCols = X_cat.shape[1]
    
    indexOfColumnToEncode = currNumOfCols - orginalNumOfCols + i
    
    ct = ColumnTransformer(transformers=
                            [('encoder', 
                              OneHotEncoder(), [indexOfColumnToEncode])], 
                           remainder='passthrough', 
                           sparse_threshold=0)
    
    X_cat = ct.fit_transform(X_cat)

In [ ]:
X_cat.shape

In [ ]:
X_num = X[:,[0,5,,9,11,12,13,14]]

X = np.concatenate((X_num, X_cat),asix=1)

In [ ]:
 from sklearn.preprocessingimport StandardScaler 

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
from keras.models import Sequntial 
from keras.layers import Dense

classifire = Sequntial()

classifire.add(Dense(units=128 ,activation='relu'))

classifire.add(Dense(units=64 ,activation='relu'))


classifire.add(Dense(units=32 ,activation='relu'))

classifire.add(Dense(units=1 ,activation='sigmoid'))

classifire.compile(optimizer='adam',loss='binary_crossentropy')metrics=p'accuracy'])



classifierHistory = classifire.fit(X_train,y_r