In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("dataset.csv")

# only chose some field
df = df[['Date' ,'Time' ,'Latitude' ,'Longitude' ,'Depth' ,'Magnitude']]
df

             Date      Time  Latitude  Longitude   Depth  Magnitude
0      01/02/1965  13:44:18   19.2460   145.6160  131.60        6.0
1      01/04/1965  11:29:49    1.8630   127.3520   80.00        5.8
2      01/05/1965  18:05:58  -20.5790  -173.9720   20.00        6.2
3      01/08/1965  18:49:43  -59.0760   -23.5570   15.00        5.8
4      01/09/1965  13:32:50   11.9380   126.4270   15.00        5.8
...           ...       ...       ...        ...     ...        ...
23407  12/28/2016   8:22:12   38.3917  -118.8941   12.30        5.6
23408  12/28/2016   9:13:47   38.3777  -118.8957    8.80        5.5
23409  12/28/2016  12:38:51   36.9179   140.4262   10.00        5.9
23410  12/29/2016  22:30:19   -9.0283   118.6639   79.00        6.3
23411  12/30/2016  20:08:28   37.3973   141.4103   11.94        5.5

[23412 rows x 6 columns]

In [3]:
import datetime

current_datetime = datetime.datetime.now()
print("Now is : ", current_datetime)

timestamp = current_datetime.timestamp()

print("Time stamp (seconds) : " , timestamp)

Now is :  2026-10-06 16:53:00.163307
Time stamp (seconds) :  1791291180.163307

In [4]:
import datetime

timestamps = []
for _, row in df.iterrows():
    try:
        d = row['Date']
        t = row['Time']
        
        full_date_string= d + " " + t
        
        full_date = datetime.datetime.strptime(full_date_string, '%m/%d/%Y %H:%M:%S')
        
        timestamp = full_date.timestamp()
        
        timestamps.append(timestamp)
        
    except Exception:
        timestamps.append('ValueError')

In [5]:
df['Timestamp'] = timestamp
df = df.drop(['Date', 'Time'], axis=1)
df = df[df.Timestamp != 'ValueError']
df['Timestamp'] = df['Timestamp'].astype(float)
df.head()

   Latitude  Longitude  Depth  Magnitude     Timestamp
0    19.246    145.616  131.6        6.0  1.483114e+09
1     1.863    127.352   80.0        5.8  1.483114e+09
2   -20.579   -173.972   20.0        6.2  1.483114e+09
3   -59.076    -23.557   15.0        5.8  1.483114e+09
4    11.938    126.427   15.0        5.8  1.483114e+09

In [6]:
# !pip install basemap

In [7]:
# from mpl_toolkits.basemap import Basemap

# m = Basemap()

# longitudes = df["Longitude"].tolist()

# latitudes = df["Latitude"].tolist()

# x,y = m(longitudes,latitudes)

# fig = plt.figure(figsize=(12,10))

# plt.title("All affected areas")

# m.plot(x, y, "o", markersize = 2, color = 'blue')

# m.drawcoastlines()

# m.fillcontinents(color='coral',lake_color='aqua')

# m.drawmapboundary()

# m.drawcountries()

# plt.show()